apiVersion: v1
kind: Service
metadata:
  name: data-tier
  labels:
    app: microservices
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
  selector:
    tier: data # select pods with label tier=data
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-tier
  labels:
    app: microservices
    tier: data # label for data-tier deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: data # select pods with label tier=data
  template:
    metadata:
      labels:
        app: microservices # label for the pod
        tier: data
    spec:
      containers:
      - name: redis
        image: redis:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 6379